name: keyboard_visibility_example
description: Keyboard visibility example

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility:
    path: ../

dev_dependencies:
  pedantic: 1.9.0

flutter:
  uses-material-design: true
